services:
  backend:
    profiles: [backend]
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '${BACKEND_HOST_PORT:-8000}:8000'
  frontend:
    profiles: [frontend]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '${FRONTEND_HOST_PORT:-80}:80'