# Generated by Django 6.0.1 on 2026-02-02 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle_Posting',
            fields=[
                ('posting_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_id', models.IntegerField()),
                ('category', models.CharField(choices=[('Hot Meals', 'hot meals'), ('Fresh Produce', 'fresh produce'), ('Prepared Salads', 'prepared salads'), ('Bakery', 'bakery'), ('Desserts', 'desserts'), ('Dairy', 'dairy')], max_length=30)),
                ('contents', models.CharField(max_length=50)),
                ('allergens', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('quantity_remaining', models.IntegerField()),
                ('price', models.FloatField()),
                ('pickup_window', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('consumer_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=50)),
                ('streak', models.IntegerField(default=0)),
                ('badges', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('claim_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('no-show', 'No show'), ('collected', 'Collected'), ('expired', 'Expired')], max_length=20)),
                ('no_show_reason', models.CharField(max_length=50)),
                ('collected_at', models.DateTimeField()),
                ('consumer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.consumer')),
                ('posting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.bundle_posting')),
            ],
        ),
    ]
