# Generated by Django 5.2 on 2026-03-21 04:43

from django.db import migrations


def insert_initial_badges(apps, schema_editor):
    Badges = apps.get_model("core", "Badges")

    badges = [
        {"name": "Eco Starter", "min_co2": 100, "min_categories": 0},
        {"name": "Eco Friend", "min_co2": 500, "min_categories": 0},
        {"name": "Climate Hero", "min_co2": 1000, "min_categories": 0},
        {"name": "Planet Saver", "min_co2": 10000, "min_categories": 0},
        {"name": "Explorer", "min_categories": 2, "min_co2": 0},
        {"name": "Discoverer", "min_categories": 3, "min_co2": 0},
        {"name": "Adventurer", "min_categories": 4, "min_co2": 0},
        {"name": "Master", "min_categories": 6, "min_co2": 0},
    ]

    for b in badges:
        if not Badges.objects.filter(name=b["name"]).exists():
            Badges.objects.create(
                name=b["name"],
                min_co2=b["min_co2"],
                min_categories=b["min_categories"],
            )


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(insert_initial_badges),
    ]
