# Generated by Django 5.2 on 2026-01-20 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=20)),
                ("streak", models.IntegerField()),
                ("badges", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=6)),
                ("opening_hours", models.CharField(max_length=20)),
                ("contact_stub", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Bundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=20)),
                ("contents", models.TextField()),
                ("allergens", models.TextField()),
                ("quantity", models.IntegerField()),
                ("price", models.FloatField()),
                ("pickup_window", models.CharField(max_length=20)),
                ("status", models.IntegerField()),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.seller",
                    ),
                ),
            ],
        ),
    ]
