# Generated by Django 5.2 on 2026-02-10 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumer",
            name="password",
            field=models.CharField(default="password", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seller",
            name="password",
            field=models.CharField(default="password", max_length=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim_code", models.CharField(max_length=20)),
                ("status", models.IntegerField()),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.bundle",
                    ),
                ),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.consumer",
                    ),
                ),
            ],
        ),
    ]
