# Generated by Django 5.2 on 2026-02-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_consumer_password_seller_password_reservation"),
    ]

    operations = [
        migrations.CreateModel(
            name="BundlePosting",
            fields=[
                ("posting_id", models.IntegerField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=20)),
                ("contents", models.TextField()),
                ("allergens", models.TextField(blank=True, null=True)),
                ("quantity", models.IntegerField()),
                ("price", models.FloatField()),
                ("pickup_window", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"managed": False},
        ),
    ]
