# Generated by Django 5.2 on 2026-02-14 16:24

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_bundleposting_alter_reservation_options"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE marketplace_reservation RENAME COLUMN bundle_id TO posting_id;",
            reverse_sql="ALTER TABLE marketplace_reservation RENAME COLUMN posting_id TO bundle_id;",
        ),
    ]

