# Generated by Django 5.2 on 2026-02-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_rename_bundle_id_to_posting_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bundleposting",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={},
        ),
    ]
