# Generated by Django 5.2 on 2026-01-26 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BundlePosting',
            fields=[
                ('posting_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('contents', models.TextField(blank=True, null=True)),
                ('allergens', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('quantity_remaining', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_window', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bundle_posting',
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('consumer_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('streak', models.IntegerField(default=0)),
                ('badges', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consumer',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('opening_hours', models.TextField(blank=True, null=True)),
                ('contact_stub', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'seller',
            },
        ),
        migrations.CreateModel(
            name='ForecastOutput',
            fields=[
                ('output_id', models.AutoField(primary_key=True, serialize=False)),
                ('predicted_reservations', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predicted_no_show_prob', models.DecimalField(decimal_places=2, max_digits=3)),
                ('confidence', models.CharField(blank=True, max_length=255, null=True)),
                ('rationale', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bundleposting')),
            ],
            options={
                'db_table': 'forecast_output',
            },
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('responded', 'Responded'), ('resolved', 'Resolved')], max_length=20)),
                ('seller_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.consumer')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bundleposting')),
            ],
            options={
                'db_table': 'issue_report',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('claim_code', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('collected', 'Collected'), ('no-show', 'No-show'), ('expired', 'Expired')], max_length=20)),
                ('no_show_reason', models.TextField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consumer')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bundleposting')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='ForecastInput',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField()),
                ('time_window', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weather_flag', models.IntegerField(default=0)),
                ('observed_reservations', models.IntegerField()),
                ('observed_no_show', models.IntegerField()),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.seller')),
            ],
            options={
                'db_table': 'forecast_input',
            },
        ),
        migrations.AddField(
            model_name='bundleposting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seller'),
        ),
    ]
