# Generated by Django 5.2 on 2026-03-12 19:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergen",
            fields=[
                ("allergen_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "allergens",
            },
        ),
        migrations.CreateModel(
            name="Badges",
            fields=[
                ("badge_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=30)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "badges",
            },
        ),
        migrations.CreateModel(
            name="BundlePosting",
            fields=[
                ("posting_id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=255)),
                ("contents", models.TextField(blank=True, null=True)),
                ("allergens", models.TextField(blank=True, null=True)),
                ("quantity", models.IntegerField()),
                ("quantity_remaining", models.IntegerField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pickup_window", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "bundle_posting",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Consumer",
            fields=[
                ("consumer_id", models.AutoField(primary_key=True, serialize=False)),
                ("display_name", models.CharField(max_length=255)),
                ("streak", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "consumer",
            },
        ),
        migrations.CreateModel(
            name="ForecastOutput",
            fields=[
                ("output_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "predicted_reservations",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "predicted_no_show_prob",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("confidence", models.CharField(blank=True, max_length=255, null=True)),
                ("rationale", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "posting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bundleposting",
                    ),
                ),
            ],
            options={
                "db_table": "forecast_output",
            },
        ),
        migrations.CreateModel(
            name="IssueReport",
            fields=[
                ("issue_id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("responded", "Responded"),
                            ("resolved", "Resolved"),
                        ],
                        max_length=20,
                    ),
                ),
                ("seller_response", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consumer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.consumer",
                    ),
                ),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bundleposting",
                    ),
                ),
            ],
            options={
                "db_table": "issue_report",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("reservation_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("claim_code", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("collected", "Collected"),
                            ("no-show", "No-show"),
                            ("expired", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("no_show_reason", models.TextField(blank=True, null=True)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.consumer"
                    ),
                ),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bundleposting",
                    ),
                ),
            ],
            options={
                "db_table": "reservation",
            },
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("seller_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("opening_hours", models.TextField(blank=True, null=True)),
                (
                    "contact_stub",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "seller",
            },
        ),
        migrations.CreateModel(
            name="ForecastInput",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("day_of_week", models.IntegerField()),
                ("time_window", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("weather_flag", models.IntegerField(default=0)),
                ("observed_reservations", models.IntegerField()),
                ("observed_no_show", models.IntegerField()),
                ("unreserved_stock", models.IntegerField(blank=True, null=True)),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.seller",
                    ),
                ),
            ],
            options={
                "db_table": "forecast_input",
            },
        ),
        migrations.CreateModel(
            name="ConsumerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("stars", models.IntegerField()),
                ("title", models.CharField(max_length=50)),
                ("review", models.TextField(blank=True, null=True)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.consumer"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.seller"
                    ),
                ),
            ],
            options={
                "db_table": "consumer_review",
            },
        ),
        migrations.CreateModel(
            name="ConsumerReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.consumer"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.seller"
                    ),
                ),
            ],
            options={
                "db_table": "consumer_report",
            },
        ),
        migrations.AddField(
            model_name="bundleposting",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.seller"
            ),
        ),
        migrations.CreateModel(
            name="SellerReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.consumer"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.seller"
                    ),
                ),
            ],
            options={
                "db_table": "seller_report",
            },
        ),
        migrations.CreateModel(
            name="SellerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("stars", models.IntegerField()),
                ("title", models.CharField(max_length=50)),
                ("review", models.TextField(blank=True, null=True)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.consumer"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.seller"
                    ),
                ),
            ],
            options={
                "db_table": "seller_review",
            },
        ),
        migrations.CreateModel(
            name="BundleAllergens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allergen_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.allergen"
                    ),
                ),
                (
                    "bundle_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bundleposting",
                    ),
                ),
            ],
            options={
                "unique_together": {("bundle_id", "allergen_id")},
            },
        ),
        migrations.CreateModel(
            name="BadgeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.badges"
                    ),
                ),
                (
                    "consumer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.consumer",
                    ),
                ),
            ],
            options={
                "unique_together": {("badge_id", "consumer_id")},
            },
        ),
    ]
