# Generated by Django 5.2 on 2026-03-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundleposting",
            name="category",
            field=models.CharField(
                choices=[
                    ("bakery", "Bakery"),
                    ("dairy", "Dairy"),
                    ("desserts", "Desserts"),
                    ("fresh_produce", "Fresh_Produce"),
                    ("hot_meals", "Hot_Meals"),
                    ("prepared_salads", "Prepared_Salads"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="consumer",
            name="co2_saved",
            field=models.FloatField(default=0),
        ),
    ]
