# Generated by Django 5.2 on 2026-02-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecastinput",
            name="unreserved_stock",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
