# Generated by Django 5.2 on 2026-03-19 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_consumer_created_at_maintainer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badges',
            name='earned_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badgemapping',
            name='consumer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='badges', to='core.consumer'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
