# Generated by Django 5.2 on 2026-02-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_forecastinput_unreserved_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecastinput",
            name="unreserved_stock",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
