# Generated by Django 5.2 on 2026-02-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_forecastinput_unreserved_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundleposting',
            name='quantity_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
