# Generated by Django 5.2 on 2026-03-10 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_bundleposting_quantity_remaining"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badges",
            fields=[
                ("badge_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=30)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "badges",
            },
        ),
        migrations.RemoveField(
            model_name="consumer",
            name="badges",
        ),
        migrations.AddField(
            model_name="consumer",
            name="password",
            field=models.CharField(default="password", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seller",
            name="password",
            field=models.CharField(default="password", max_length=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="BadgeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consumer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.consumer",
                    ),
                ),
                (
                    "badge_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.badges"
                    ),
                ),
            ],
            options={
                "unique_together": {("badge_id", "consumer_id")},
            },
        ),
    ]
