# Generated by Django 5.2 on 2026-03-10 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_badges_remove_consumer_badges_consumer_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('allergen_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'allergens',
            },
        ),
        migrations.CreateModel(
            name='ConsumerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consumer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seller')),
            ],
            options={
                'db_table': 'consumer_report',
            },
        ),
        migrations.CreateModel(
            name='ConsumerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stars', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('review', models.TextField(blank=True, null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consumer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seller')),
            ],
            options={
                'db_table': 'consumer_review',
            },
        ),
        migrations.CreateModel(
            name='SellerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consumer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seller')),
            ],
            options={
                'db_table': 'seller_report',
            },
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stars', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('review', models.TextField(blank=True, null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consumer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seller')),
            ],
            options={
                'db_table': 'seller_review',
            },
        ),
        migrations.CreateModel(
            name='BundleAllergens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.allergen')),
                ('bundle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bundleposting')),
            ],
            options={
                'unique_together': {('bundle_id', 'allergen_id')},
            },
        ),
    ]
