# Generated by Django 5.2 on 2026-03-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_bundleposting_allergens_seed_allergens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('maintainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'maintainer',
            },
        ),
    ]
